const{ hasUncaughtExceptionCaptureCallback } = require("process");

function funcToTest(input) {

}